### ISSUE TITLE
Catching errors

### ISSUE THREAD

**Issue by ardeaf** [skvvv/pikapy#2]
Getting the below error periodically. Result of the module you're using not catching the error, but I'm not sure how to edit it myself.  
```
Traceback (most recent call last):
  File "/usr/bin/pikapy", line 9, in <module>
    load_entry_point('Pikapy==0.2', 'console_scripts', 'pikapy')()
  File "/usr/lib/python2.7/site-packages/pikapy/console.py", line 60, in entry
    args.username, args.password, args.email, args.email_tag
  File "/usr/lib/python2.7/site-packages/pikapy/accountcreator.py", line 404, in random_account
    try_username, password, try_email
  File "/usr/lib/python2.7/site-packages/pikapy/accountcreator.py", line 244, in create_account
    resp_code=200
  File "/usr/lib/python2.7/site-packages/pikapy/accountcreator.py", line 99, in request
    resp = self.send(prepped)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 667, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(54 bytes read)', IncompleteRead(54 bytes read))

```

**Comment by skvvv** [comment]
This could be a pogoapi error.
Can you elaborate a bit more? You say you are getting it periodically?
Can you post which command are you running?

**Comment by skvvv** [comment]
https://github.com/skvvv/pikapy/blob/master/pikapy/accountcreator.py#L89

This is where the error is raised.
Could you try making a simple try-except pass loop and see if it works?

I would but have no idea how to recreate it.

**Comment by ardeaf** [comment]
Sorry for the non-response -- I've been trying to find cloud hosting that isn't banned, been unsuccessful.  I'll be switching over to VPN soon and I'll let you know if I can recreate the error on my home computer.

**Comment by skvvv** [comment]
@ardeaf I fixed it a week ago, but account generator is dead as niantic implemented captcha.
