### ISSUE TITLE
Nothing happening when running pikapy

### ISSUE THREAD

**Issue by moggd** [skvvv/pikapy#21]
Was using this earlier today with no issues.

However, now when I try running my normal pikapy -p password -c 5 from terminal and nothing happens.  It just sits there hung.  No errors or anything.

**Comment by aldarund** [comment]
Same. hangup on some ssl read

 File "/opt/webapps/pogomap/bin/pikapy", line 9, in <module>
    load_entry_point('Pikapy==0.2', 'console_scripts', 'pikapy')()
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pikapy/console.py", line 60, in entry
    args.username, args.password, args.email, args.email_tag
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pikapy/accountcreator.py", line 404, in random_account
    try_username, password, try_email
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pikapy/accountcreator.py", line 296, in create_account
    resp_code=200
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pikapy/accountcreator.py", line 99, in request
    resp = self.send(prepped)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 194, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1320, in recv
    result = _lib.SSL_read(self._ssl, buf, bufsiz)

**Comment by Mickey32111** [comment]
+1

**Comment by Gruutak** [comment]
It got stuck here too... 

```
Traceback (most recent call last):
  File "/usr/local/bin/pikapy", line 9, in <module>
    load_entry_point('Pikapy==v0.2', 'console_scripts', 'pikapy')()
  File "/usr/local/lib/python2.7/dist-packages/pikapy/console.py", line 60, in entry
    args.username, args.password, args.email, args.email_tag
  File "/usr/local/lib/python2.7/dist-packages/pikapy/accountcreator.py", line 404, in random_account
    try_username, password, try_email
  File "/usr/local/lib/python2.7/dist-packages/pikapy/accountcreator.py", line 244, in create_account
    resp_code=200
  File "/usr/local/lib/python2.7/dist-packages/pikapy/accountcreator.py", line 99, in request
    resp = self.send(prepped)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 179, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 194, in recv
    data = self.connection.recv(*args, **kwargs)
```

**Comment by yayes2** [comment]
Same problem.

**Comment by RMSInterject** [comment]
It's happening to me too. I thought it was just me, but I'm glad it's not. Unfortunately I was only able to make 3 accounts before it stopped working.

**Comment by moggd** [comment]
Looks like they added a Captcha to the PTC registration form.  RIP

**Comment by owenheaps** [comment]
^

**Comment by skvvv** [comment]
It is captcha, we'll try to do some black magic to fix this.

**Comment by aldarund** [comment]
well, maybe add support for some captcha solving service like deathbycaptcha/2captcha/whatever  ( yes they are paid and who will be using will need to provide valid creds for it), but i dont know other method for bypassing recaptcha.

**Comment by TheDDoSFriend** [comment]
Were working on making it work with the captcha. Be patient:)

**Comment by WillGSX** [comment]
Same deal.  Thanks for the work fellas, love the script!

**Comment by skvvv** [comment]
@WillGSX fixed that for you :D

**Comment by TheDDoSFriend** [comment]
Unfortunately, we cannot find a way to bypass the captcha. We are very sorry, and we hope you enjoyed the script while it worked. Thank you for all the support.

**Comment by khag7** [comment]
I think there is still value in this project. 

What if you automate the data entry and submission but still require a user to sit and monitor the process (to do the captcha). 

I can be sitting watching tv. Your script is running, entering random emails and passwords and usernames and cycling through at a reasonable pace. When the server sends the HTML for the page, instead of ignoring it, display a browser window where I can see and interact with the captcha form. I do it, click submit, and the script continues on.

**Comment by TheDDoSFriend** [comment]
We will try to do something that can get it working again, but we cant promise that it will.

**Comment by Dem0N-SPb** [comment]
Maybe you can do so to show the CAPTCHA to the user and the user input characters?

**Comment by Yossi** [comment]
http://www.cs.columbia.edu/~polakis/papers/sivakorn_eurosp16.pdf

you need an aged google tracking cookie

**Comment by SnowyWolfy** [comment]
From cffi callback <bound method
 type._lock_cb of <class 'crypto
graphy.hazmat.bindings.openssl.b
inding.Binding'>>:

**Comment by jasondinh** [comment]
Even if you can't get the reCaptcha working, please split out the code to accept TOS. Otherwise we'll need to login to every single account and accept. Thanks!

**Comment by Mickey32111** [comment]
Yeah, the TOS acceptance code should still work. It's easy enough to create the accounts yourself, just a little time consuming. It's accepting the TOS which is the biggest pain in the arse.

**Comment by Lionir** [comment]
PogoTos accepts all the TOS for a list of accounts.

**Comment by compuguy** [comment]
@Mickey32111 At least it should add an option to generate the username and password so we can manually enter them in the browser. Bulk username and password generation is still a useful part of this app.

**Comment by TheDDoSFriend** [comment]
We have a possible solution that we will try to implement. It may work, but its not guaranteed.

**Comment by Baklap4** [comment]
Hmmm would be very nice @theddosfriend!

**Comment by paul30001** [comment]
@khag7 Yes.
Way, way better, than creating or finding hundreds throwaway emails and then manually entering data for each PTC acc.
@TheDDoSFriend @skvvv Also, why not a Captcha solving service? I would certainly pay for that. But I can imagine the hustle that comes with payment processing.

**Comment by paul30001** [comment]
@skvvv idk accounts are still working for me. I guess Niantic hasn't gotten to my batch yet :(

**Comment by TheDDoSFriend** [comment]
https://github.com/skvvv/pikapy/blob/master/README.md

**Comment by paul30001** [comment]
@TheDDoSFriend what about that link? The website is Great news! Any ETA on that?

**Comment by Spiritvn** [comment]
@TheDDoSFriend could you update the readme that show how we can use the ToS script only? I can create the accounts myself, but the accept ToS and training step's really pain.

**Comment by skvvv** [comment]
fixed
