### ISSUE TITLE
Message: 'chromedriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by aviram83** [skvvv/pikapy#36]
I had this issue with ubuntu 16.04 64bit

The solution I have found:

$ **sudo apt-get install chromium-chromedriver**
$ **PATH="${PATH}":/usr/lib/chromium-browser/**
$ **pikay**

**Comment by aczone** [comment]
i got the same problem, and i tried op's solution
then it prompts out selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.21,platform=Linux 4.1.19-v7+ armv7l)
im on rpi3 ubuntu 16.04 as well, thanks

**Comment by JerryCoke** [comment]
I have following Problem :((

`Attempting to create user crugstrevprang:passw0rd. Opening browser...
Traceback (most recent call last):
  File "/usr/local/bin/pikapy", line 11, in <module>
    load_entry_point('Pikapy==0.3', 'console_scripts', 'pikapy')()
  File "/usr/local/lib/python2.7/dist-packages/pikapy/console.py", line 68, in e                                                                                        ntry
    account_info = pikapy.random_account(args.username, args.password, args.emai                                                                                        l, args.birthday, args.plusmail, x, args.numeric, args.dry)
  File "/usr/local/lib/python2.7/dist-packages/pikapy/accountcreator.py", line 2                                                                                        17, in random_account
    account_created = True if dry else create_account(try_username, password, tr                                                                                        y_email, try_birthday)
  File "/usr/local/lib/python2.7/dist-packages/pikapy/accountcreator.py", line 1                                                                                        08, in create_account
    driver = webdriver.Chrome()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriv                                                                                        er.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service                                                                                        .py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executabl                                                                                        e needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chrome                                                                                        driver/home

Exception AttributeError: "'Service' object has no attribute 'process'" in <boun                                                                                        d method Service.__del__ of <selenium.webdriver.chrome.service.Service object at                                                                                         0x7f39ac078a90>> ignored
`  


Has somebody a solution :dart:
