### ISSUE TITLE
AssertionError (assert driver.current_url == "{}/parents/sign-up".format(BASE_URL))

### ISSUE THREAD

**Issue by Cr4nkSt4r** [skvvv/pikapy#43]
Hello,
I'm on Ubuntu 16.04.1 and get the following error, maybe someone can help:

```
pikapy
Attempting to create user modcrevchup:gezfrubbriv. Opening browser...
Step 1: Verifying age using birthday: 1988-01-22
Step 2: Entering account details
Traceback (most recent call last):
  File "/usr/local/bin/pikapy", line 9, in <module>
    load_entry_point('Pikapy==0.3', 'console_scripts', 'pikapy')()
  File "/usr/local/lib/python2.7/dist-packages/pikapy/console.py", line 60, in entry
    account_info = pikapy.random_account(args.username, args.password, args.email, args.birthday, args.plusmail)
  File "/usr/local/lib/python2.7/dist-packages/pikapy/accountcreator.py", line 208, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday)
  File "/usr/local/lib/python2.7/dist-packages/pikapy/accountcreator.py", line 127, in create_account
    assert driver.current_url == "{}/parents/sign-up".format(BASE_URL)
AssertionError
```

**Comment by feliksalbright** [comment]
I was getting the exact same error. Just close down the browser and all your terminal windows and try it again. Let us know if it continues.

**Comment by Cr4nkSt4r** [comment]
At the moment, I use Pikaptcha. I don't get any errors and it works like a charm.
If I get the time today I'll test ne newest pikapy release again with your mentions.
