### ISSUE TITLE
Error with windows. 

### ISSUE THREAD

**Issue by wetakekills** [skvvv/pikapy#49]
Traceback (most recent call last):
  File "C:\Python27\Scripts\pikapy-script.py", line 9, in <module>
    load_entry_point('Pikapy==0.3', 'console_scripts', 'pikapy')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2570, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2230, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2236, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\pikapy\console.py", line 7, in <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi

any idea whats happening? @skvvv

**Comment by newjanson** [comment]
Try:
pip install git+https://github.com/keyphact/pgoapi.git
And tell me if it works. Also have you done pip install git+https://github.com/keyphact/pgoapi.git?

**Comment by wetakekills** [comment]
i tried, but it gave me this error.

Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\temp\\pip-build-wv5qvy\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\user\appdata\local\temp\pip-cqkd80-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\user\appdata\local\temp\pip-build-wv5qvy\xxhash\

**Comment by newjanson** [comment]
According to this issue: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2734
downloading this https://www.microsoft.com/en-us/download/details.aspx?id=44266 will do the trick.

**Comment by newjanson** [comment]
@wetakekills did it work?

**Comment by skvvv** [comment]
@newjanson that's in the prerequisites link for windows
