### ISSUE TITLE
Service chromedriver unexpectedly exited

### ISSUE THREAD

**Issue by pixelquadrat** [skvvv/pikapy#68]
When running pikapy on my raspberry pi 3 (raspbian jessy) I get the following error:

`Attempting to create user runtclopblisk:blubswompstod. Opening browser...
Traceback (most recent call last):
  File "./pikapy", line 11, in <module>
    load_entry_point('Pikapy==0.3', 'console_scripts', 'pikapy')()
  File "/opt/python/lib/python2.7/site-packages/pikapy/console.py", line 68, in entry
    account_info = pikapy.random_account(args.username, args.password, args.email, args.birthday, args.plusmail, x, args.numeric, args.dry)
  File "/opt/python/lib/python2.7/site-packages/pikapy/accountcreator.py", line 217, in random_account
    account_created = True if dry else create_account(try_username, password, try_email, try_birthday)
  File "/opt/python/lib/python2.7/site-packages/pikapy/accountcreator.py", line 108, in create_account
    driver = webdriver.Chrome()
  File "/opt/python/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/opt/python/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 86, in start
    self.assert_process_still_running()
  File "/opt/python/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 99, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127

Exception RuntimeError: RuntimeError('sys.path must be a list of directory names',) in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x754bb410>> ignored
`

**Comment by mikaoras** [comment]
same error on all my linux

**Comment by Theo1996** [comment]
me too

**Comment by faroukelloumi** [comment]
A solution ?

**Comment by eliorkilometer** [comment]
I'm experiencing the same problem, running webdriver.Chrome(path_to_chrome_driver) on a linux server

**Comment by koalazak** [comment]
me to on debian. Any solution?

**Comment by iandersen** [comment]
I have this issue as well
