### ISSUE TITLE
Import error: No module know pgoapi

### ISSUE THREAD

**Issue by Luclu7gaming** [skvvv/pikapy#72]
Hi, when I launch pikaapy (on debian jessie, chromium installed), it says 

`Traceback (most recent call last):
  File "/usr/local/bin/pikapy", line 9, in <module>
    load_entry_point('Pikapy==v0.3', 'console_scripts', 'pikapy')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pikapy/console.py", line 7, in <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi
root@vps1:/home/luclu7/.vnc# pikapy
Traceback (most recent call last):
  File "/usr/local/bin/pikapy", line 9, in <module>
    load_entry_point('Pikapy==v0.3', 'console_scripts', 'pikapy')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pikapy/console.py", line 7, in <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi`
And it do nothing, it's do same on windows.

**Comment by hinfaits** [comment]
On Debian, try:
 `pip install git+https://github.com/tejado/pgoapi`
