### ISSUE TITLE
The bot seems to run fine but once it opens chrome chrome only says "Data;" then closes

### ISSUE THREAD

**Issue by epic2000o** [skvvv/pikapy#75]
Running...
Attempting to create user kuspgrumpblet:password. Opening browser...
                                                    Traceback (most recent call last):
  File "C:\Python27\Scripts\pikapy-script.py", line 9, in <module>
    load_entry_point('Pikapy==0.3', 'console_scripts', 'pikapy')()
  File "c:\python27\lib\site-packages\pikapy\console.py", line 68, in entry
    account_info = pikapy.random_account(args.username, args.password, args.email, args.birthday, args.plusmail, x, args.numeric, args.dry)
  File "c:\python27\lib\site-packages\pikapy\accountcreator.py", line 217, in random_account
    account_created = True if dry else create_account(try_username, password, try_email, try_birthday)
  File "c:\python27\lib\site-packages\pikapy\accountcreator.py", line 108, in create_account
    driver = webdriver.Chrome()
  File "c:\python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"10640.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 10.0.14393 x86_64)

Complete!

**Comment by plan291037** [comment]
https://chromedriver.storage.googleapis.com/index.html?path=2.25/

**Comment by kilado94** [comment]
got same error..cant solve it :/

**Comment by Theo1996** [comment]
got exactly the same problem tried reinstalling chrome and drivers nothing

**Comment by epic2000o** [comment]
I solved the issue you need to put the chrome driver in the pythons 27 folder and out a copy in the scripts folder this should solve it

**Comment by Theo1996** [comment]
**Thank you very much Sir epic2000o**, it helped me resolve my problem ,time to make more accounts and sell.
I downloaded the driver 2.25 from the above link and put it in the pyhton27 folder and the python27/Scripts folder,so to copies in total even though i had them there it seems either the drivers were outdated or too new or of different version between the folders.

**Comment by GabrieleLoCastro** [comment]
i have the same problem, it opens chrome chrome only says "Data;" but i'm on mac and i don't find where to put the chromedriver anyone  can help me? 

this is my terminal output:

Attempting to create user zumnikpug:dremkengruct. Opening browser...
Traceback (most recent call last):
  File "/usr/local/bin/pikapy", line 9, in <module>
    load_entry_point('Pikapy==0.3', 'console_scripts', 'pikapy')()
  File "/usr/local/lib/python2.7/site-packages/pikapy/console.py", line 68, in entry
    account_info = pikapy.random_account(args.username, args.password, args.email, args.birthday, args.plusmail, x, args.numeric, args.dry)
  File "/usr/local/lib/python2.7/site-packages/pikapy/accountcreator.py", line 217, in random_account
    account_created = True if dry else create_account(try_username, password, try_email, try_birthday)
  File "/usr/local/lib/python2.7/site-packages/pikapy/accountcreator.py", line 109, in create_account
    driver.set_window_size(600, 600)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 846, in set_window_size
    'windowHandle': windowHandle})
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot get automation extension
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":8411,542124}}
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.1 x86_64)

**Comment by BitRulez** [comment]
i have the same problem, it opens chrome chrome only says "Data;" but i'm on mac and i don't find where to put the chromedriver anyone  can help me? 

this is my terminal output:

Attempting to create user zumnikpug:dremkengruct. Opening browser...
Traceback (most recent call last):
  File "/usr/local/bin/pikapy", line 9, in <module>
    load_entry_point('Pikapy==0.3', 'console_scripts', 'pikapy')()
  File "/usr/local/lib/python2.7/site-packages/pikapy/console.py", line 68, in entry
    account_info = pikapy.random_account(args.username, args.password, args.email, args.birthday, args.plusmail, x, args.numeric, args.dry)
  File "/usr/local/lib/python2.7/site-packages/pikapy/accountcreator.py", line 217, in random_account
    account_created = True if dry else create_account(try_username, password, try_email, try_birthday)
  File "/usr/local/lib/python2.7/site-packages/pikapy/accountcreator.py", line 109, in create_account
    driver.set_window_size(600, 600)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 846, in set_window_size
    'windowHandle': windowHandle})
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot get automation extension
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":8411,542124}}
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.1 x86_64)

**Comment by epic2000o** [comment]
This issue is solved but I case you can't find this BitRulz you copy the chrome driver and then paste it in the python 27folder

**Comment by epic2000o** [comment]
@Theo1996 can you please give me an account that's level 26? My computer isn't working rn thanks

**Comment by epic2000o** [comment]
@ButRulez pleae go theough the entire thread if you can't find it please @me

**Comment by Theo1996** [comment]
@epic2000o  So you want to buy an account or just to be donated one?Right now i am botting a new account and is currently at level 18 i think its gonna take a while to reach lvl 26 like 2 weeks and thats when the API bots come out.Also if you want to continue this contact me by email (theonipponotaku@hotmail.com)or skype on my selly page or ownedcore.Since this is not a trade thread for PokeGO :-)

**Comment by plan291037** [comment]
pip install --upgrade git+https://github.com/keyphact/pgoapi.git

**Comment by plan291037** [comment]
https://sites.google.com/a/chromium.org/chromedriver/downloads
